import { randomBytes } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

import {
  AGENTS_FILE,
  CLI_BIN,
  ENV,
  PRODUCT_NAME,
  REVALIDATE_ROUTE,
  SDK_PACKAGE,
  TYPES_FILE,
} from '@product'

import { generateTypes } from '../../sdk/src/typegen'
import { agentsBlock, mergeAgentsFile } from './agents-file'
import type { NextApp } from './detect'
import { displayPath } from './detect'
import { ENV_FILE, writeEnvFile } from './env-file'
import { ensureIgnored } from './gitignore'
import { CONFIG_DIR } from './local-config'
import type { NextConfigResult } from './next-config'
import { ensureHtmlLimitedBots } from './next-config'

/**
 * Everything `init` and `link` both do to a customer's project, in one place.
 *
 * `link` is `init` minus project creation, so keeping the file-writing here
 * guarantees the two cannot drift — a project connected by `link` gets exactly
 * the same `.env.local`, types, `AGENTS.md` and revalidate route as one created
 * by `init`, which is what makes `init`'s idempotent second run meaningful.
 *
 * Every step is safe to repeat. Nothing here overwrites a file the customer
 * owns without being asked to (`force`); the only file rewritten unconditionally
 * is the generated types file, which says so in its own header.
 */

/** 256 bits. This secret is the only thing standing between a stranger and a
 *  cache purge on the customer's site. */
const REVALIDATE_SECRET_BYTES = 32

export function generateRevalidateSecret(): string {
  return randomBytes(REVALIDATE_SECRET_BYTES).toString('base64url')
}

/* ── the revalidate route handler (§10, §11) ──────────────────────────────── */

export function revalidateRouteSource(): string {
  return [
    `import { createRevalidateRoute } from '${SDK_PACKAGE}/revalidate'`,
    '',
    '/**',
    ` * ${PRODUCT_NAME}'s publish webhook lands here and purges the affected cache tags.`,
    ` * Generated by \`${CLI_BIN} init\`. Safe to keep as-is; deleting it means published`,
    ' * content never reaches the site.',
    ' *',
    ` * Authenticated with ${ENV.revalidateSecret}.`,
    ' */',
    'export const { POST } = createRevalidateRoute()',
    '',
  ].join('\n')
}

export function revalidateRoutePath(app: NextApp): string {
  return join(app.appDir, ...REVALIDATE_ROUTE.split('/').filter((part) => part.length > 0), 'route.ts')
}

/* ── input / output ───────────────────────────────────────────────────────── */

export interface ScaffoldKeys {
  readonly read: string
  readonly write?: string | undefined
  readonly preview?: string | undefined
}

export interface ScaffoldInput {
  readonly app: NextApp
  readonly projectId: string
  readonly projectName: string | undefined
  readonly apiBaseUrl: string
  readonly keys: ScaffoldKeys
  readonly revalidateSecret: string
  readonly writeTypes: boolean
  /** Overwrite a revalidate route the customer has since edited. */
  readonly force: boolean
}

export type FileOutcome = 'created' | 'updated' | 'unchanged' | 'kept'

export interface WrittenFile {
  readonly path: string
  readonly label: string
  readonly outcome: FileOutcome
}

export interface ScaffoldResult {
  readonly env: WrittenFile
  /** Which environment variables the write actually touched. */
  readonly envChanged: readonly string[]
  readonly types: WrittenFile | undefined
  readonly agents: WrittenFile
  readonly revalidate: WrittenFile
  /** M21.1 — metadata has to reach AI crawlers inside the `<head>`. */
  readonly nextConfig: NextConfigResult
  readonly gitignoreAdded: readonly string[]
}

/* ── steps ────────────────────────────────────────────────────────────────── */

function writeIfChanged(path: string, contents: string): FileOutcome {
  const existed = existsSync(path)
  if (existed && readFileSync(path, 'utf8') === contents) return 'unchanged'
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, contents, 'utf8')
  return existed ? 'updated' : 'created'
}

function scaffoldEnv(input: ScaffoldInput): { file: WrittenFile; changed: readonly string[] } {
  const updates = new Map<string, string>([
    [ENV.apiUrl, input.apiBaseUrl],
    [ENV.projectId, input.projectId],
    [ENV.readKey, input.keys.read],
    [ENV.revalidateSecret, input.revalidateSecret],
  ])
  // Absent keys are not written as empty strings: an empty value would make the
  // SDK believe preview is configured and fail at request time instead of at
  // `previewClient()`, where the error names the missing variable.
  if (input.keys.write !== undefined) updates.set(ENV.writeKey, input.keys.write)
  if (input.keys.preview !== undefined) updates.set(ENV.previewKey, input.keys.preview)

  const written = writeEnvFile(
    input.app.root,
    updates,
    `# ${PRODUCT_NAME} — written by \`${CLI_BIN} init\`. Server-side only; never NEXT_PUBLIC_.`,
  )

  return {
    file: {
      path: written.path,
      label: ENV_FILE,
      outcome: written.created ? 'created' : written.changed.length === 0 ? 'unchanged' : 'updated',
    },
    changed: written.changed,
  }
}

function scaffoldTypes(input: ScaffoldInput): WrittenFile {
  const path = join(input.app.root, TYPES_FILE)
  return { path, label: TYPES_FILE, outcome: writeIfChanged(path, generateTypes()) }
}

function scaffoldAgents(input: ScaffoldInput): WrittenFile {
  const path = join(input.app.root, AGENTS_FILE)
  const existing = existsSync(path) ? readFileSync(path, 'utf8') : undefined
  const merged = mergeAgentsFile(
    existing,
    agentsBlock({
      projectId: input.projectId,
      projectName: input.projectName,
      apiBaseUrl: input.apiBaseUrl,
      appDirLabel: input.app.appDirLabel,
    }),
  )

  if (existing === merged.text) {
    return { path, label: AGENTS_FILE, outcome: 'unchanged' }
  }
  writeFileSync(path, merged.text, 'utf8')
  return { path, label: AGENTS_FILE, outcome: existing === undefined ? 'created' : 'updated' }
}

function scaffoldRevalidateRoute(input: ScaffoldInput): WrittenFile {
  const path = revalidateRoutePath(input.app)
  const label = displayPath(input.app.root, path)
  const source = revalidateRouteSource()

  if (existsSync(path) && !input.force) {
    const current = readFileSync(path, 'utf8')
    // Someone edited the handler. Ours is two lines; theirs may wrap it in auth
    // or logging, and silently replacing that would be the worst kind of help.
    return { path, label, outcome: current === source ? 'unchanged' : 'kept' }
  }
  return { path, label, outcome: writeIfChanged(path, source) }
}

/* ── the whole scaffold ───────────────────────────────────────────────────── */

export function scaffold(input: ScaffoldInput): ScaffoldResult {
  const env = scaffoldEnv(input)
  const gitignore = ensureIgnored(input.app.root, [ENV_FILE, `${CONFIG_DIR}/`])

  return {
    env: env.file,
    envChanged: env.changed,
    types: input.writeTypes ? scaffoldTypes(input) : undefined,
    agents: scaffoldAgents(input),
    revalidate: scaffoldRevalidateRoute(input),
    nextConfig: ensureHtmlLimitedBots({
      root: input.app.root,
      cliBin: CLI_BIN,
      display: (absolute) => displayPath(input.app.root, absolute),
    }),
    gitignoreAdded: gitignore.added,
  }
}
